Exception in thread Thread-1 (send_typing_action):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/machine_learning/bot_bulder/bot_builder/apps/worker/commands_handler.py", line 124, in send_typing_action
    while c == True:
NameError: name 'c' is not defined
